baseURL: http://dh-tech.github.io
disablePathToLower: true
languageCode: en-us
title: DHTech

menu:
  main:
  - name: about
    pageRef: /about
  - name: news
    pageRef: /news/
  - name: meetups
    pageRef: /workshops/
  - name: blog
    pageRef: /blog/
  - name: sig
    pageRef: /SIG
  - name: working groups
    pageRef: /working-groups

markup:
  goldmark:
    renderer:
      unsafe: true   # allow raw html in content

theme:
  - "github.com/chipzoller/hugo-clarity"

# clarity-specific configuration

mainSections:
  - blog
  - news
  - workshops

permalinks:
  news: /:year/:month/:day/:slug/

params:
  logo: "logos/logo.png"
  subtitle: "An ADHO Special Interest Group"
  mobileNavigation: right
  showReadTime: false
  showShare: false
